name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checks:
    uses: self:gianluca/gitea-ci/.gitea/workflows/node-app-ci.yml@v1.0.3
    with:
      node-version: '22'
      run-tests: true
      run-lint: true
      run-typecheck: true
      run-prisma-generate: false
      run-build: true
